[2023-12-11 14:59:37,106] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 14:59:37] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:00:21,171] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:00:21] "OPTIONS /produto?nome=cerveja HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:00:21,503] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:00:21] "DELETE /produto?nome=cerveja HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:13:09,525] WARNING del_produto() L135  Erro ao deletar produto #'cerveja', Produto não encontrado na base :/ - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\app.py L135 
[2023-12-11 15:13:09,536] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:13:09] "[33mDELETE /produto?nome=cerveja HTTP/1.1[0m" 404 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:13:13,007] WARNING del_produto() L135  Erro ao deletar produto #'cerveja', Produto não encontrado na base :/ - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\app.py L135 
[2023-12-11 15:13:13,008] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:13:13] "[33mDELETE /produto?nome=cerveja HTTP/1.1[0m" 404 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:13:24,898] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:13:24] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:13:59,624] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:13:59] "DELETE /produto?nome=água HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:14:06,168] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:14:06] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:14:23,284] WARNING del_produto() L135  Erro ao deletar produto #'cerveja', Produto não encontrado na base :/ - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\app.py L135 
[2023-12-11 15:14:23,286] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:14:23] "[33mDELETE /produto?nome=cerveja HTTP/1.1[0m" 404 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:14:36,952] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:14:36] "DELETE /produto?nome=vinho HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:14:42,657] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:14:42] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:14:55,677] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:14:55] "OPTIONS /produto?nome=cerveja HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:14:55,687] WARNING del_produto() L135  Erro ao deletar produto #'cerveja', Produto não encontrado na base :/ - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\app.py L135 
[2023-12-11 15:14:55,689] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:14:55] "[33mDELETE /produto?nome=cerveja HTTP/1.1[0m" 404 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:15:30,380] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:15:30] "POST /produto HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:16:08,929] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 15:16:08,933] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:16:08] "[35m[1mGET /produto?nome=cerveja HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:16:24,822] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 15:16:24,826] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:16:24] "[35m[1mGET /produto?nome=água HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:17:03,887] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:17:03] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:17:03,901] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:17:03] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:17:03,904] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:17:03] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:17:03,908] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:17:03] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:17:04,136] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:17:04] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 15:17:04,151] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 15:17:04] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
